const EVENTS_SERVICE_GUID = process.env.EVENTS_SERVICE_GUID || "n6j4dcwwpexjhwbyc7vyqdrk";
const EVENTS_COLLECTION_NAME = process.env.EVENTS_COLLECTION_NAME || "popagame-events";
const EVENTS_SERVICE_MOCKED_UP = process.env.EVENTS_SERVICE_MOCKED_UP || "true";

const ANSWERS_SERVICE_GUID = process.env.ANSWERS_SERVICE_GUID;
const ANSWERS_COLLECTION_NAME = process.env.ANSWERS_COLLECTION_NAME || "popagame-answers";
const ANSWERS_SERVICE_MOCKED_UP = process.env.ANSWERS_SERVICE_MOCKED_UP || "true";

module.exports.EVENTS_SERVICE_GUID = EVENTS_SERVICE_GUID;
module.exports.EVENTS_COLLECTION_NAME = EVENTS_COLLECTION_NAME;
module.exports.EVENTS_SERVICE_MOCKED_UP = EVENTS_SERVICE_MOCKED_UP;

module.exports.ANSWERS_SERVICE_GUID = ANSWERS_SERVICE_GUID;
module.exports.ANSWERS_COLLECTION_NAME = ANSWERS_COLLECTION_NAME;
module.exports.ANSWERS_SERVICE_MOCKED_UP = ANSWERS_SERVICE_MOCKED_UP;